# -*- coding: utf-8 -*-
"""TMSJ-Model A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/reuf-Alsharif/58b01c09271e044f585f40c37d911172/tmsj_model_a_full_pipeline.ipynb

#  Model A - Legal Information Extraction System

#  PART 1 — Setup + Data Loading
"""

import os
print(os.listdir("/kaggle/input"))

# PART 1 — Imports & Configuration

import os
import json
import logging
from pathlib import Path
from typing import List, Dict, Any
import numpy as np
import pandas as pd
import torch
import warnings
from sklearn.model_selection import train_test_split

# ── stdlib ─────────────────────────────────────────────────────────────────────
import os
import json
import logging
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ── third-party ────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# HuggingFace
from datasets import Dataset, DatasetDict, ClassLabel, Sequence, Value
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
    EarlyStoppingCallback,
)

from pathlib import Path

class Config:
    BASE_DIR = Path("/kaggle/input/datasets/janaalotaibi/model-a")

    BASELINE_LAWS = BASE_DIR / "01_baseline_laws.jsonl"
    SEGMENTED_CASES = BASE_DIR / "03_segmented.csv"
    ENTITY_SUMMARY = BASE_DIR / "04_entities.csv"
    TENSORS_FILE = BASE_DIR / "05_tensors.pt"

    MODEL_A_LABEL_MAP = BASE_DIR / "model_a_label_map.json"
    MODEL_A_TRAIN = BASE_DIR / "model_a_ner_bio_train.jsonl"
    MODEL_A_VAL = BASE_DIR / "model_a_ner_bio_val.jsonl"
    MODEL_A_TEST = BASE_DIR / "model_a_ner_bio_test.jsonl"

    OUTPUT_DIR = Path("/kaggle/working/outputs")
    CHECKPOINT_DIR = Path("/kaggle/working/checkpoints")
    MODEL_A_OUTPUT_DIR = OUTPUT_DIR / "model_a"

    RANDOM_SEED = 42
    MAX_LEN = 512
    MODEL_NAME = "aubmindlab/bert-base-arabertv02"

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    MODEL_A_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Setup
def setup():
    Config.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    Config.CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s — %(levelname)s — %(message)s"
    )

    np.random.seed(Config.RANDOM_SEED)
    torch.manual_seed(Config.RANDOM_SEED)

    logging.info("Environment ready")


logger = logging.getLogger(__name__)

# File Loaders
def load_jsonl(path: Path) -> List[Dict]:
    data = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            data.append(json.loads(line))
    return data


def load_directory_json(path: Path) -> List[Dict]:
    data = []
    for file in path.glob("*.json"):
        with open(file, "r", encoding="utf-8") as f:
            data.append(json.load(f))
    return data


def load_directory_jsonl(path: Path) -> List[Dict]:
    data = []
    for file in path.glob("*.jsonl"):
        data.extend(load_jsonl(file))
    return data

# Load ALL Required Inputs
class DataLoader:

    def __init__(self):
        self.segmented_cases = []
        self.extracted_entities = []
        self.train = []
        self.val = []
        self.test = []
        self.legal_corpus = []

    def load_all(self):
        logger.info("Loading segmented cases...")
        self.segmented_cases = load_directory_jsonl(Config.SEGMENTED_CASES)

        logger.info("Loading extracted entities...")
        self.extracted_entities = load_directory_jsonl(Config.EXTRACTED_ENTITIES)

        logger.info("Loading train/val/test...")
        self.train = load_jsonl(Config.TRAIN_FILE)
        self.val = load_jsonl(Config.VAL_FILE)
        self.test = load_jsonl(Config.TEST_FILE)

        logger.info("Loading legal corpus...")
        self.legal_corpus = load_jsonl(Config.LEGAL_CORPUS)

        logger.info(f"Segmented: {len(self.segmented_cases)}")
        logger.info(f"Entities: {len(self.extracted_entities)}")
        logger.info(f"Train: {len(self.train)} | Val: {len(self.val)} | Test: {len(self.test)}")
        logger.info(f"Legal corpus: {len(self.legal_corpus)}")

        return self

# Utility — Merge Case Sources
class CaseMerger:
    """
    Merge segmented cases with extracted entities using case_id
    """

    @staticmethod
    def merge(segmented: List[Dict], entities: List[Dict]) -> Dict[str, Dict]:

        entity_map = {e["case_id"]: e for e in entities}

        merged = {}

        for case in segmented:
            cid = case["case_id"]

            merged[cid] = {
                "case_id": cid,
                "segments": case.get("segments", []),
                "entities": entity_map.get(cid, {})
            }

        logging.info(f"Merged cases: {len(merged)}")

        return merged

# Save Helpers
def save_jsonl(data: List[Dict], path: Path):
    with open(path, "w", encoding="utf-8") as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")


def save_json(data: Dict, path: Path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Ready
def initialize_pipeline():
    setup()
    loader = DataLoader().load_all()
    merged_cases = CaseMerger.merge(loader.segmented_cases, loader.extracted_entities)

    return loader, merged_cases

import os

for root, dirs, files in os.walk("/kaggle/input"):
    print(root)
    for f in files:
        print("  ", f)

def check_model_a_files():
    files_to_check = {
        "SEGMENTED_CASES": Config.SEGMENTED_CASES,
        "ENTITY": Config.ENTITY_SUMMARY,
        "TENSORS_FILE": Config.TENSORS_FILE,
        "MODEL_A_LABEL_MAP": Config.MODEL_A_LABEL_MAP,
        "MODEL_A_TRAIN": Config.MODEL_A_TRAIN,
        "MODEL_A_VAL": Config.MODEL_A_VAL,
        "MODEL_A_TEST": Config.MODEL_A_TEST,
    }

    print("=" * 50)
    print("MODEL A FILE CHECK")
    print("=" * 50)

    for name, path in files_to_check.items():
        status = "FOUND" if path.exists() else "MISSING"
        print(f"{name:<20} -> {status} -> {path}")

check_model_a_files()

with open(Config.MODEL_A_LABEL_MAP, "r", encoding="utf-8") as f:
    label_map = json.load(f)

print("Labels:")
print(label_map["labels"])
print("\nNumber of labels:", len(label_map["labels"]))

def read_jsonl_sample(path, n=2):
    samples = []
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            samples.append(json.loads(line))
            if i + 1 >= n:
                break
    return samples

samples = read_jsonl_sample(Config.MODEL_A_TRAIN, n=2)

for i, s in enumerate(samples, 1):
    print(f"\n===== SAMPLE {i} =====")
    print("case_id:", s.get("case_id"))
    print("segment_id:", s.get("segment_id"))
    print("tokens[:30]:", s.get("tokens", [])[:30])
    print("bio_tags[:30]:", s.get("bio_tags", [])[:30])

from datasets import Dataset
import json

def load_jsonl_to_dataset(file_path):
    data = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            data.append(json.loads(line))
    return Dataset.from_list(data)

train_ds = load_jsonl_to_dataset(Config.MODEL_A_TRAIN)

def find_bio_errors(dataset):
    errors = []

    for i, example in enumerate(dataset):
        tags = example["bio_tags"]

        for j in range(1, len(tags)):
            prev_tag = tags[j-1]
            curr_tag = tags[j]

            # لو الاثنين B لنفس الكيان → خطأ
            if prev_tag.startswith("B-") and curr_tag.startswith("B-"):
                if prev_tag[2:] == curr_tag[2:]:
                    errors.append((i, j, prev_tag, curr_tag))

    return errors


errors = find_bio_errors(train_ds)

print("Number of BIO errors:", len(errors))
print("Sample errors:", errors[:10])

def fix_repeated_B_tags(dataset):
    fixed_data = []
    fixed_count = 0

    for example in dataset:
        example = dict(example)
        tags = list(example["bio_tags"])

        for i in range(1, len(tags)):
            prev_tag = tags[i - 1]
            curr_tag = tags[i]

            if prev_tag.startswith(("B-", "I-")) and curr_tag.startswith("B-"):
                prev_label = prev_tag[2:]
                curr_label = curr_tag[2:]

                if prev_label == curr_label:
                    tags[i] = "I-" + curr_label
                    fixed_count += 1

        example["bio_tags"] = tags
        fixed_data.append(example)

    return fixed_data, fixed_count


fixed_train_data, fixed_count = fix_repeated_B_tags(train_ds)

print("Fixed count:", fixed_count)

fixed_train_data, fixed_count = fix_repeated_B_tags(train_ds)
print("Fixed count:", fixed_count)

from datasets import Dataset

train_ds_fixed = Dataset.from_list(fixed_train_data)

errors_after = find_bio_errors(train_ds_fixed)

print("BIO errors before:", len(errors))
print("Fixed count:", fixed_count)
print("BIO errors after:", len(errors_after))
print("Sample errors after:", errors_after[:10])

val_ds = load_jsonl_to_dataset(Config.MODEL_A_VAL)
test_ds = load_jsonl_to_dataset(Config.MODEL_A_TEST)

fixed_val_data, val_fixed_count = fix_repeated_B_tags(val_ds)
fixed_test_data, test_fixed_count = fix_repeated_B_tags(test_ds)

from datasets import Dataset

val_ds_fixed = Dataset.from_list(fixed_val_data)
test_ds_fixed = Dataset.from_list(fixed_test_data)

print("Val errors after:", len(find_bio_errors(val_ds_fixed)))
print("Test errors after:", len(find_bio_errors(test_ds_fixed)))

def find_I_without_B(dataset):
    errors = []

    for i, example in enumerate(dataset):
        tags = example["bio_tags"]

        for j in range(len(tags)):
            tag = tags[j]

            if tag.startswith("I-"):
                label = tag[2:]

                if j == 0:
                    errors.append((i, j, tag, "START"))
                else:
                    prev = tags[j-1]

                    if not (prev == "B-" + label or prev == "I-" + label):
                        errors.append((i, j, tag, prev))

    return errors


for name, ds in [
    ("train", train_ds_fixed),
    ("val", val_ds_fixed),
    ("test", test_ds_fixed)
]:
    errs = find_I_without_B(ds)
    print(name, "I-without-B errors:", len(errs))
    print("sample:", errs[:5])

def fix_I_without_B(dataset):
    fixed_data = []
    fixed_count = 0

    for example in dataset:
        example = dict(example)
        tags = list(example["bio_tags"])

        for i in range(len(tags)):
            tag = tags[i]

            if tag.startswith("I-"):
                label = tag[2:]

                if i == 0:
                    tags[i] = "B-" + label
                    fixed_count += 1
                else:
                    prev = tags[i - 1]

                    if not (prev == "B-" + label or prev == "I-" + label):
                        tags[i] = "B-" + label
                        fixed_count += 1

        example["bio_tags"] = tags
        fixed_data.append(example)

    return Dataset.from_list(fixed_data), fixed_count

train_ds_final, train_i_fixed = fix_I_without_B(train_ds_fixed)
val_ds_final, val_i_fixed = fix_I_without_B(val_ds_fixed)
test_ds_final, test_i_fixed = fix_I_without_B(test_ds_fixed)

print("Train I fixed:", train_i_fixed)
print("Val I fixed:", val_i_fixed)
print("Test I fixed:", test_i_fixed)

print("Train repeated B:", len(find_bio_errors(train_ds_final)))
print("Val repeated B:", len(find_bio_errors(val_ds_final)))
print("Test repeated B:", len(find_bio_errors(test_ds_final)))

print("Train I errors:", len(find_I_without_B(train_ds_final)))
print("Val I errors:", len(find_I_without_B(val_ds_final)))
print("Test I errors:", len(find_I_without_B(test_ds_final)))

from collections import Counter
import json

def label_distribution(path, max_records=2000):
    counter = Counter()
    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            rec = json.loads(line)
            counter.update(rec.get("bio_tags", []))
            if i + 1 >= max_records:
                break
    return counter

dist = label_distribution(Config.MODEL_A_TRAIN, max_records=2000)

for label, count in dist.most_common():
    print(label, count)

import json

def validate_bio_file(path, max_check=500):
    bad = 0
    checked = 0

    with open(path, "r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            rec = json.loads(line)
            tokens = rec.get("tokens", [])
            tags = rec.get("bio_tags", [])

            if len(tokens) != len(tags):
                bad += 1
                print(f"Mismatch in record {i}: tokens={len(tokens)}, tags={len(tags)}")

            checked += 1
            if checked >= max_check:
                break

    print(f"Checked records: {checked}")
    print(f"Mismatches: {bad}")

"""---
#  Part 2: Data Processing & Cleaning
---

##  Load Data & Fix BIO Tagging Errors
"""

validate_bio_file(Config.MODEL_A_TRAIN)
validate_bio_file(Config.MODEL_A_VAL)
validate_bio_file(Config.MODEL_A_TEST)

"""# MODEL A — READER / EXTRACTOR  

> **Goal**: Extract structured legal information from Saudi commercial judgments and legal texts.


> **Use**: *AraLegal-BERT* otherwise create a training-ready transformer-based extraction pipeline with a working baseline

# 1. Environment Setup & Dependency Installation
"""

import transformers, datasets, accelerate
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("accelerate:", accelerate.__version__)

!pip install -q transformers datasets seqeval evaluate accelerate

from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)
import evaluate

# Install required libraries
!pip install -q transformers[torch] datasets seqeval sentencepiece
!pip install -q pandas numpy

"""# 2. Google Drive Integration"""

from pathlib import Path

# 📂 مسارات الحفظ في Kaggle
CHECKPOINT_DIR = Path("/kaggle/working/model_a/checkpoints")
FINAL_MODEL_DIR = Path("/kaggle/working/model_a/final_model")

# إنشاء الفولدرات
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
FINAL_MODEL_DIR.mkdir(parents=True, exist_ok=True)

print("✅ Paths ready:")
print("Checkpoints:", CHECKPOINT_DIR)
print("Final model:", FINAL_MODEL_DIR)

from pathlib import Path

# Version name
RUN_NAME = "model_a_v3"

# 📂 Base (مكان الحفظ في Kaggle)
BASE_DIR = Path("/kaggle/working/TMSJfinal")

# Paths
CHECKPOINT_DIR = BASE_DIR / RUN_NAME / "checkpoints"
FINAL_MODEL_DIR = BASE_DIR / RUN_NAME / "final_model"

# Create folders
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
FINAL_MODEL_DIR.mkdir(parents=True, exist_ok=True)

print("✅ Paths ready:")
print("Run name:", RUN_NAME)
print("Checkpoints:", CHECKPOINT_DIR)
print("Final model:", FINAL_MODEL_DIR)

"""# 3. Data Loading & Preprocessing"""

from pathlib import Path

class Config:
    # 📂 مكان البيانات (Kaggle input)
    BASE_DIR = Path("/kaggle/input/datasets/janaalotaibi/model-a")

    MODEL_A_LABEL_MAP = BASE_DIR / "model_a_label_map.json"
    MODEL_A_TRAIN = BASE_DIR / "model_a_ner_bio_train.jsonl"
    MODEL_A_VAL   = BASE_DIR / "model_a_ner_bio_val.jsonl"
    MODEL_A_TEST  = BASE_DIR / "model_a_ner_bio_test.jsonl"

    # 💾 مكان الحفظ (Kaggle working)
    OUTPUT_DIR = Path("/kaggle/working/model_a_training_outputs")

    MODEL_NAME = "aubmindlab/bert-base-arabertv02"
    MAX_LEN = 512
    RANDOM_SEED = 42

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print(Config.MODEL_A_TRAIN.exists())
print(Config.MODEL_A_VAL.exists())
print(Config.MODEL_A_TEST.exists())
print(Config.MODEL_A_LABEL_MAP.exists())

def load_jsonl(path):
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line))
    return records

train_records = load_jsonl(Config.MODEL_A_TRAIN)
val_records = load_jsonl(Config.MODEL_A_VAL)
test_records = load_jsonl(Config.MODEL_A_TEST)

print("Train:", len(train_records))
print("Val:", len(val_records))
print("Test:", len(test_records))

train_dataset = Dataset.from_list(train_records)
val_dataset = Dataset.from_list(val_records)
test_dataset = Dataset.from_list(test_records)

print(train_dataset.column_names)
print(val_dataset.column_names)
print(test_dataset.column_names)

"""# 4. Tokenization & Subword Label Alignment"""

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(Config.MODEL_NAME)

print("✅ Tokenizer loaded")

tokenizer = AutoTokenizer.from_pretrained(Config.MODEL_NAME)

keep_cols = ["input_ids", "attention_mask", "labels"]

train_dataset = train_dataset.remove_columns([c for c in train_dataset.column_names if c not in keep_cols])
val_dataset = val_dataset.remove_columns([c for c in val_dataset.column_names if c not in keep_cols])
test_dataset = test_dataset.remove_columns([c for c in test_dataset.column_names if c not in keep_cols])

print(train_dataset)
print(val_dataset)
print(test_dataset)

"""# 5. Load Pretrained Model"""

with open(Config.MODEL_A_LABEL_MAP, "r", encoding="utf-8") as f:
    label_map_data = json.load(f)

label_list = label_map_data["labels"]
label2id = label_map_data["label2id"]
id2label = {v: k for k, v in label2id.items()}

print("Labels:", label_list)
print("Number of labels:", len(label_list))
print("label2id:", label2id)

from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    Config.MODEL_NAME,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

print("✅ Model loaded")

from transformers import AutoModelForTokenClassification

model = AutoModelForTokenClassification.from_pretrained(
    Config.MODEL_NAME,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

print("✅ Model loaded")

"""# 6. Data Collator"""

from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

print("✅ Data collator ready")

"""# 7. Define Metrics"""

import numpy as np
import evaluate

seqeval = evaluate.load("seqeval")

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = []
    true_labels = []

    for pred, lab in zip(predictions, labels):
        current_preds = []
        current_labels = []
        for p_i, l_i in zip(pred, lab):
            if l_i != -100:
                current_preds.append(label_list[p_i])
                current_labels.append(label_list[l_i])
        true_predictions.append(current_preds)
        true_labels.append(current_labels)

    results = seqeval.compute(predictions=true_predictions, references=true_labels)

    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

print("✅ Metrics ready")

"""# 8. Training Arguments"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=str(CHECKPOINT_DIR),
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    seed=Config.RANDOM_SEED,
    report_to="none"
)

print("✅ Training arguments ready")

"""# 9. Initialize Trainer"""

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("✅ Trainer ready")

print(train_dataset[0])

print(train_ds_fixed[0]["bio_tags"][:30])

"""# 10. Start Training"""

import json
from datasets import Dataset

def load_jsonl(path):
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            records.append(json.loads(line))
    return records

train_records = load_jsonl(Config.MODEL_A_TRAIN)
val_records = load_jsonl(Config.MODEL_A_VAL)
test_records = load_jsonl(Config.MODEL_A_TEST)

train_dataset = Dataset.from_list(train_records)
val_dataset = Dataset.from_list(val_records)
test_dataset = Dataset.from_list(test_records)

print(train_dataset.column_names)
print(val_dataset.column_names)
print(test_dataset.column_names)

"""---
#  Part 3: Model Building & Training
---

##  Training Environment Setup
"""

with open(Config.MODEL_A_LABEL_MAP, "r", encoding="utf-8") as f:
    label_map_data = json.load(f)

label_list = label_map_data["labels"]
label2id = label_map_data["label2id"]
id2label = {v: k for k, v in label2id.items()}

print(label_list)

def encode_labels(example):
    example["labels"] = [label2id[tag] for tag in example["bio_tags"]]
    return example

train_dataset = train_dataset.map(encode_labels)
val_dataset = val_dataset.map(encode_labels)
test_dataset = test_dataset.map(encode_labels)

print(train_dataset.column_names)
print(train_dataset[0])

def convert_tags_to_ids(example):
    example["labels"] = [label2id[tag] for tag in example["bio_tags"]]
    return example

train_dataset = train_dataset.map(convert_tags_to_ids)

print(train_dataset[0]["bio_tags"][:30])
print(train_dataset[0]["labels"][:30])

# Fix repeated B-tags directly on current train_dataset
fixed_train_data, fixed_count = fix_repeated_B_tags(train_dataset)

from datasets import Dataset
train_dataset = Dataset.from_list(fixed_train_data)

print("Fixed count:", fixed_count)
print(train_dataset[0]["bio_tags"][:30])

def convert_tags_to_ids(example):
    example["labels"] = [label2id[tag] for tag in example["bio_tags"]]
    return example

train_dataset = train_dataset.map(convert_tags_to_ids)

print(train_dataset[0]["bio_tags"][:30])
print(train_dataset[0]["labels"][:30])

fixed_val_data, val_fixed_count = fix_repeated_B_tags(val_dataset)
val_dataset = Dataset.from_list(fixed_val_data)

fixed_test_data, test_fixed_count = fix_repeated_B_tags(test_dataset)
test_dataset = Dataset.from_list(fixed_test_data)

print("Val fixed count:", val_fixed_count)
print("Test fixed count:", test_fixed_count)

val_dataset = val_dataset.map(convert_tags_to_ids)
test_dataset = test_dataset.map(convert_tags_to_ids)

print(val_dataset[0]["bio_tags"][:30])
print(val_dataset[0]["labels"][:30])

print("Train BIO errors:", len(find_bio_errors(train_dataset)))
print("Val BIO errors:", len(find_bio_errors(val_dataset)))
print("Test BIO errors:", len(find_bio_errors(test_dataset)))

raw_datasets = DatasetDict({
    "train": train_dataset,
    "validation": val_dataset,
    "test": test_dataset
})

from datasets import DatasetDict

raw_datasets = DatasetDict({
    "train": train_dataset,
    "validation": val_dataset,
    "test": test_dataset
})

print(raw_datasets)

print(raw_datasets["train"][0].keys())

tokenized_datasets = raw_datasets.remove_columns(
    ["tokens", "bio_tags", "case_id", "segment_id"]
)

print(tokenized_datasets)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("✅ Trainer rebuilt successfully")

trainer.train()

trainer.save_model(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)

import os
print(os.listdir(FINAL_MODEL_DIR))

import shutil

shutil.make_archive(
    str(FINAL_MODEL_DIR),
    'zip',
    str(FINAL_MODEL_DIR)
)

import shutil

shutil.copy(
    "/kaggle/working/model_a_v3/final_model.zip",
    "/kaggle/working/final_model.zip"
)

from IPython.display import FileLink
FileLink('/kaggle/working/final_model.zip')

import os
print(os.path.exists('/kaggle/working/model_a_v3/final_model.zip'))

import os

print(os.listdir(FINAL_MODEL_DIR))

trainer.save_model(str(FINAL_MODEL_DIR))

print(os.listdir(FINAL_MODEL_DIR))

import os
print(os.listdir(CHECKPOINT_DIR))

print(FINAL_MODEL_DIR)

import shutil

zip_path = "/kaggle/working/model_a_final.zip"

shutil.make_archive(
    base_name=zip_path.replace(".zip", ""),
    format="zip",
    root_dir=str(FINAL_MODEL_DIR)
)

print("✅ Model zipped at:", zip_path)

"""# Extracting and Loading Training from ZIP File"""

import shutil

shutil.unpack_archive(
    "/kaggle/working/model_a_final.zip",
    "/kaggle/working/model_a_loaded"
)

from transformers import AutoModelForTokenClassification, AutoTokenizer

model_path = "/kaggle/working/model_a_loaded"

model = AutoModelForTokenClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

print("✅ Model loaded successfully")

"""# 11. Evaluate Model"""

val_results = trainer.evaluate(val_dataset)
test_results = trainer.evaluate(test_dataset)

print("Validation Results:", val_results)
print("Test Results:", test_results)

logs = trainer.state.log_history

train_loss = []
eval_loss = []
epochs = []

for log in logs:
    if "loss" in log and "epoch" in log:
        train_loss.append(log["loss"])
    if "eval_loss" in log:
        eval_loss.append(log["eval_loss"])
        epochs.append(log["epoch"])

"""**Extract Train and Validation Logs Correctly**"""

train_epochs = []
train_loss = []

eval_epochs = []
eval_loss = []
eval_f1 = []

for log in trainer.state.log_history:
    if "loss" in log and "epoch" in log and "eval_loss" not in log:
        train_epochs.append(log["epoch"])
        train_loss.append(log["loss"])

    if "eval_loss" in log and "epoch" in log:
        eval_epochs.append(log["epoch"])
        eval_loss.append(log["eval_loss"])

    if "eval_f1" in log and "epoch" in log:
        eval_f1.append(log["eval_f1"])

"""**Plot Loss Curves**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.plot(train_epochs, train_loss, marker="o", label="Train Loss")
plt.plot(eval_epochs, eval_loss, marker="o", label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

"""**Print the Values**"""

print("Train Epochs:", train_epochs)
print("Train Loss:", train_loss)
print("Eval Epochs:", eval_epochs)
print("Eval Loss:", eval_loss)
print("Eval F1:", eval_f1)

"""# 12. Testing Model A on New Text"""

model.eval()

text = "نظرت المحكمة التجارية في القضية رقم 12345 وألزمت المدعى عليه بدفع مبلغ 50000 ريال بتاريخ 1445/2/10"

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

inputs = tokenizer(text, return_tensors="pt", truncation=True)
inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)

preds = outputs.logits.argmax(dim=2)[0].tolist()
tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0].cpu())

for token, pred in zip(tokens, preds):
    print(token, "→", id2label[pred])

def clean_bert_token(token):
    return token.replace("##", "")

def merge_subwords(tokens):
    merged = []
    for tok in tokens:
        if tok.startswith("##") and merged:
            merged[-1] = merged[-1] + tok[2:]
        else:
            merged.append(tok)
    return merged

entities = []
current = []
current_label = None

for token, pred in zip(tokens, preds):
    label = id2label[pred]

    if token in ["[CLS]", "[SEP]", "[PAD]"]:
        continue

    if label.startswith("B-"):
        if current:
            merged = merge_subwords(current)
            entities.append((" ".join(merged), current_label))
        current = [token]
        current_label = label[2:]

    elif label.startswith("I-") and current:
        current.append(token)

    else:
        if current:
            merged = merge_subwords(current)
            entities.append((" ".join(merged), current_label))
            current = []

if current:
    merged = merge_subwords(current)
    entities.append((" ".join(merged), current_label))

print("🔹 Clean Extracted Entities:")
for e in entities:
    print(e)

"""# 13. Load Sample from Test Dataset"""

sample = test_records[0]
print(sample.keys())
print(sample["tokens"][:50])
print(sample["bio_tags"][:50])

"""**Step1. Inspect Sample Structure**"""

sample_tokens = sample["tokens"]
sample_tags = sample["bio_tags"]

print("Tokens:")
print(sample_tokens[:60])

print("\nGold BIO Tags:")
print(sample_tags[:60])

"""**Step 2. Display Tokens and Gold Labels**"""

def rebuild_text(tokens):
    clean_tokens = []
    for tok in tokens:
        if tok in ["[CLS]", "[SEP]", "[PAD]"]:
            continue
        if tok.startswith("##") and clean_tokens:
            clean_tokens[-1] = clean_tokens[-1] + tok[2:]
        else:
            clean_tokens.append(tok)
    return " ".join(clean_tokens)

text = rebuild_text(sample["tokens"])
print(text[:1000])

"""**Step 4. Rebuild Text from Tokenized Input**"""

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

inputs = tokenizer(text, return_tensors="pt", truncation=True)
inputs = {k: v.to(device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)

preds = outputs.logits.argmax(dim=2)[0].tolist()
pred_tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0].cpu())

"""**Step 5. Preview Reconstructed Text**"""

for token, pred in zip(pred_tokens, preds):
    print(token, "→", id2label[pred])

def extract_entities_from_prediction(tokens, predictions, id2label):
    entities = []
    current = []
    current_label = None

    for token, pred in zip(tokens, predictions):
        label = id2label[pred]

        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current:
                entities.append((" ".join(current), current_label))
            current = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current:
            current.append(token)

        else:
            if current:
                entities.append((" ".join(current), current_label))
                current = []

    if current:
        entities.append((" ".join(current), current_label))

    return entities

entities = extract_entities_from_prediction(pred_tokens, preds, id2label)

print("Predicted Entities:")
for e in entities:
    print(e)

gold_pairs = list(zip(sample["tokens"], sample["bio_tags"]))

for tok, tag in gold_pairs[:60]:
    print(tok, "→", tag)

pred_labels = [id2label[p] for p in preds]

for tok, gold, pred in zip(pred_tokens, sample_tags[:len(pred_labels)], pred_labels):
    print(f"{tok:15} | Gold: {gold:15} | Pred: {pred}")

"""# 14. Manual Evaluation and Qualitative Analysis"""

sample = test_dataset[0]

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

input_ids = torch.tensor([sample["input_ids"]]).to(device)
attention_mask = torch.tensor([sample["attention_mask"]]).to(device)

with torch.no_grad():
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)

preds = outputs.logits.argmax(dim=2)[0].cpu().tolist()

tokens = tokenizer.convert_ids_to_tokens(sample["input_ids"])

def merge_same_label_neighbors(entities):
    if not entities:
        return entities

    merged = [entities[0]]

    for item in entities[1:]:
        last = merged[-1]
        if item["label"] == last["label"]:
            last["entity"] = last["entity"] + " " + item["entity"]
        else:
            merged.append(item)

    return merged

# ========================================
# CLEAN TEXT FUNCTION
# ========================================
def fix_entity_text(text):
    parts = text.split()
    fixed = []

    for p in parts:
        p = p.replace("##", "")

        # دمج الأرقام
        if fixed and p.isdigit() and fixed[-1].isdigit():
            fixed[-1] += p
        else:
            fixed.append(p)

    # 🔥 إعادة ترتيب ذكية لرقم القضية
    digits = [p for p in fixed if p.isdigit()]
    words = [p for p in fixed if not p.isdigit()]

    case_num = ""
    year = ""

    if len(digits) >= 1:
        case_num = digits[0]

    if len(digits) >= 2:
        year = digits[1]

    # بناء النص الصحيح
    text = ""

    if "قضية" in " ".join(words) or "القضية" in " ".join(words):
        text = f"رقم القضية {case_num}"
        if year:
            text += f" لعام {year}"
    else:
        text = " ".join(fixed)

    return text.strip()



# ========================================
# EXTRACT ENTITIES FUNCTION
# ========================================
def extract_entities(tokens, labels):
    entities = []
    current = []
    current_label = None

    for tok, lab in zip(tokens, labels):

        if tok in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        tok = tok.replace("##", "")

        if lab.startswith("B-"):
            if current:
                entities.append({
                    "label": current_label,
                    "entity": fix_entity_text(" ".join(current))
                })

            current = [tok]
            current_label = lab[2:]

        elif lab.startswith("I-") and current:
            current.append(tok)

        else:
            if current:
                entities.append({
                    "label": current_label,
                    "entity": fix_entity_text(" ".join(current))
                })
                current = []
                current_label = None

    if current:
        entities.append({
            "label": current_label,
            "entity": fix_entity_text(" ".join(current))
        })

    return entities


# ========================================
# RUN
# ========================================
entities = extract_entities(tokens, pred_labels)

print("\n=== Extracted Entities ===\n")

for item in entities:
    print(f"{item['label']} ➜ {item['entity']}")

entities = extract_entities(tokens, pred_labels)

for item in entities:
    print(f"{item['label']} ➜ {item['entity']}")

"""# Loading the Trained Model A from Kaggle Dataset"""

import os

for root, dirs, files in os.walk("/kaggle/input"):
    if "config.json" in files and "model.safetensors" in files:
        print("MODEL PATH:", root)
        print(files)

from transformers import AutoTokenizer, AutoModelForTokenClassification

model_path = "/kaggle/input/datasets/ruofalshreef/model-a"

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
model = AutoModelForTokenClassification.from_pretrained(model_path, local_files_only=True)

print("Model loaded successfully ✅")

"""---
#  Part 4: Evaluation & Testing
---

##  Model Performance Evaluation
"""

import torch

def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True)

    with torch.no_grad():
        outputs = model(**inputs)

    predictions = torch.argmax(outputs.logits, dim=2)

    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = predictions[0].tolist()

    return list(zip(tokens, labels))

text = "نظرت المحكمة التجارية في القضية رقم 12345 وألزمت بدفع 50000 ريال"

result = predict(text)

for t, l in result:
    print(t, l)

"""# Export Model A Outputs for Model B"""

import json
import torch

label_list = [
    "O",
    "B-اسم_نظام", "B-تاريخ", "B-رقم_قضية", "B-مبلغ_مالي", "B-محكمة", "B-مرجع_قانوني",
    "I-اسم_نظام", "I-تاريخ", "I-رقم_قضية", "I-مبلغ_مالي", "I-محكمة", "I-مرجع_قانوني"
]

def clean_token(token):
    return token.replace("##", "")

def extract_entities_for_model_b(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entities.append({
                    "text": "".join([clean_token(t) if t.startswith("##") else " " + clean_token(t) for t in current_tokens]).strip(),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entities.append({
                    "text": "".join([clean_token(t) if t.startswith("##") else " " + clean_token(t) for t in current_tokens]).strip(),
                    "label": current_label
                })
            current_tokens = []
            current_label = None

    if current_tokens:
        entities.append({
            "text": "".join([clean_token(t) if t.startswith("##") else " " + clean_token(t) for t in current_tokens]).strip(),
            "label": current_label
        })

    return entities

case_text = "نظرت المحكمة التجارية في القضية رقم 12345 وألزمت بدفع 50000 ريال"

model_b_input = {
    "case_text": case_text,
    "model_a_entities": extract_entities_for_model_b(case_text)
}

with open("/kaggle/working/model_b_input_sample.json", "w", encoding="utf-8") as f:
    json.dump(model_b_input, f, ensure_ascii=False, indent=2)

print(model_b_input)

def join_tokens(tokens):
    text = ""

    for tok in tokens:
        if tok.startswith("##"):
            text += tok[2:]
        else:
            if text:
                text += " "
            text += tok

    return text


def clean_entity_text(text):
    unwanted_words = ["في", "على", "من", "إلى", "عن", "و"]
    words = text.split()

    while words and words[-1] in unwanted_words:
        words.pop()

    return " ".join(words)


def extract_entities_for_model_b(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entity_text = join_tokens(current_tokens)
                entities.append({
                    "text": clean_entity_text(entity_text),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entity_text = join_tokens(current_tokens)
                entities.append({
                    "text": clean_entity_text(entity_text),
                    "label": current_label
                })

            current_tokens = []
            current_label = None

    if current_tokens:
        entity_text = join_tokens(current_tokens)
        entities.append({
            "text": clean_entity_text(entity_text),
            "label": current_label
        })

    return entities

text = "نظرت المحكمة التجارية في القضية رقم 12345 وألزمت بدفع 50000 ريال"
entities = extract_entities_for_model_b(text)
print(entities)

import os

for root, dirs, files in os.walk("/kaggle/input"):
    for f in files:
        if "03_segmented" in f:
            print(os.path.join(root, f))

import pandas as pd

SEGMENTED_PATH = "/kaggle/input/datasets/ruofalshreef/segment/03_segmented (5).csv"

df = pd.read_csv(SEGMENTED_PATH)

print(df.shape)
df.head()

grouped_cases = (
    df.sort_values(["case_id", "segment_order"])
    .groupby("case_id")["segment_text"]
    .apply(lambda x: " ".join(x.astype(str)))
    .reset_index()
)

print("Number of cases:", len(grouped_cases))
grouped_cases.head()

sample_text = grouped_cases.iloc[0]["segment_text"]

entities = extract_entities_for_model_b(sample_text)

print("Text sample:")
print(sample_text[:500])

print("\nEntities:")
print(entities[:20])

def deduplicate_entities(entities):
    seen = set()
    clean_entities = []

    for ent in entities:
        key = (ent["text"], ent["label"])
        if key not in seen:
            seen.add(key)
            clean_entities.append(ent)

    return clean_entities

"case_text": text,
        "model_a_entities": entities
    })

    if i % 100 == 0:
        print(f"Processed {i}/{len(grouped_cases)}")

print(len(model_b_data))

empty_cases = [x for x in model_b_data if not x["case_text"]]
empty_entities = [x for x in model_b_data if not x["model_a_entities"]]

print("Empty texts:", len(empty_cases))
print("Empty entities:", len(empty_entities))

print(model_b_data[0])

def clean_entity_text(text):
    text = text.replace("[UNK]", "")
    text = " ".join(text.split())
    return text.strip()

def remove_duplicate_entities(entities):
    seen = set()
    unique = []
    for e in entities:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            unique.append(e)
    return unique

def filter_entities(entities):
    clean = []
    for e in entities:
        txt = e["text"]

        if len(txt) < 4:
            continue
        if "..." in txt:
            continue
        if "النظام ونصها" in txt:
            continue
        if txt == "":
            continue

        clean.append(e)

    return clean

sample_text = grouped_cases.iloc[0]["segment_text"]

entities = extract_entities_for_model_b(sample_text)
entities = [{**e, "text": clean_entity_text(e["text"])} for e in entities]
entities = remove_duplicate_entities(entities)
entities = filter_entities(entities)

print(entities)

def remove_duplicate_entities(entities):
    seen = set()
    unique = []

    for e in entities:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            unique.append(e)

    return unique

def clean_entity_text(text):
    text = text.replace("[UNK]", "")
    text = text.replace("  ", " ")
    return text.strip()

def filter_entities(entities):
    clean = []

    for e in entities:
        if len(e["text"]) < 4:
            continue
        if "..." in e["text"]:
            continue
        if "النظام ونصها" in e["text"]:
            continue

        clean.append(e)

    return clean

model_b_data = []

for i, row in grouped_cases.iterrows():
    text = row["segment_text"]

    entities = extract_entities_for_model_b(text)
    entities = [{**e, "text": clean_entity_text(e["text"])} for e in entities]
    entities = remove_duplicate_entities(entities)
    entities = filter_entities(entities)

    model_b_data.append({
        "case_id": row["case_id"],
        "case_text": text,
        "model_a_entities": entities
    })

    if i % 100 == 0:
        print(f"Processed {i}/{len(grouped_cases)}")

"""# Define Party Extraction Function

**Detect Placeholder**
"""

def is_placeholder(text):
    return "..." in text or "(...)" in text

"""**Replace Based on Label**"""

def fix_party_entity(entity):
    text = entity["text"]
    label = entity["label"]

    if is_placeholder(text):
        if label == "مدعي":
            text = "[PLAINTIFF]"
        elif label == "مدعى_عليه":
            text = "[DEFENDANT]"

    return {
        "text": text,
        "label": label
    }

sample_text = grouped_cases.iloc[0]["segment_text"]

# استخراج
party_entities = extract_parties_from_text(sample_text)

# تطبيق placeholder
party_entities = [fix_party_entity(e) for e in party_entities]

print(party_entities)

import re

def extract_parties_from_text(text):
    parties = []

    plaintiff_pattern = r"المدّ?عي\s*:\s*(.*?)(?=\s+المدّ?عى عليه\s*:|\n|$)"

    defendant_pattern = (
        r"المدّ?عى عليه\s*:\s*(.*?)"
        r"(?=\s+الحمدلله|\s+الحمد لله|\s+تتلخص|\s+وقائع|\s+الاسباب|\s+حكمت|\n|$)"
    )

    plaintiff = re.search(plaintiff_pattern, text)
    defendant = re.search(defendant_pattern, text)

    if plaintiff:
        parties.append({
            "text": clean_entity_text(plaintiff.group(1)),
            "label": "مدعي"
        })

    if defendant:
        parties.append({
            "text": clean_entity_text(defendant.group(1)),
            "label": "مدعى_عليه"
        })

    return parties

party_entities = extract_parties_from_text(sample_text)
party_entities = [fix_party_entity(e) for e in party_entities]

print(party_entities)

def extract_parties_from_text(text):
    parties = []

    plaintiff_pattern = r"المدّ?عي\s*:\s*(.*?)(?=\s+المدّ?عى عليه\s*:|\n|$)"

    defendant_pattern = (
        r"المدّ?عى عليه\s*:\s*(.*?)"
        r"(?=\s+الحمدلله|\s+الحمد لله|\s+تتلخص|\s+وقائع|\s+الاسباب|\s+حكمت|\n|$)"
    )

    plaintiff = re.search(plaintiff_pattern, text)
    defendant = re.search(defendant_pattern, text)

    # ✔ إذا موجود
    if plaintiff:
        parties.append({
            "text": clean_entity_text(plaintiff.group(1)),
            "label": "مدعي"
        })
    else:
        #  fallback
        parties.append({
            "text": "[PLAINTIFF]",
            "label": "مدعي"
        })

    if defendant:
        parties.append({
            "text": clean_entity_text(defendant.group(1)),
            "label": "مدعى_عليه"
        })
    else:
        # 🔥 fallback
        parties.append({
            "text": "[DEFENDANT]",
            "label": "مدعى_عليه"
        })

    return parties

test_text = "نظرت المحكمة التجارية في القضية رقم 12345 وأصدرت الحكم..."

print(extract_parties_from_text(test_text))

for i, row in grouped_cases.head(5).iterrows():
    text = row["segment_text"]

    parties = extract_parties_from_text(text)

    print(f"\nCase {i}")
    print(parties)

"""# Structured Input for Model B"""

import torch

label_list = [
    "O",
    "B-اسم_نظام", "B-تاريخ", "B-رقم_قضية", "B-مبلغ_مالي", "B-محكمة", "B-مرجع_قانوني",
    "I-اسم_نظام", "I-تاريخ", "I-رقم_قضية", "I-مبلغ_مالي", "I-محكمة", "I-مرجع_قانوني"
]

def join_tokens(tokens):
    text = ""
    for tok in tokens:
        if tok.startswith("##"):
            text += tok[2:]
        else:
            if text:
                text += " "
            text += tok
    return text

def extract_entities_for_model_b(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entities.append({
                    "text": join_tokens(current_tokens),
                    "label": current_label
                })
            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entities.append({
                    "text": join_tokens(current_tokens),
                    "label": current_label
                })
            current_tokens = []
            current_label = None

    if current_tokens:
        entities.append({
            "text": join_tokens(current_tokens),
            "label": current_label
        })

    return entities

from transformers import AutoTokenizer, AutoModelForTokenClassification

model_path = "/kaggle/input/datasets/ruofalshreef/model-a"  # أو المسار حقك

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
model = AutoModelForTokenClassification.from_pretrained(model_path, local_files_only=True)

print("✅ tokenizer + model جاهزين")

test_entities = extract_entities_for_model_b(grouped_cases.iloc[0]["segment_text"])
print(test_entities[:5])

parties = extract_parties_from_text(text)
parties = [fix_party_entity(e) for e in parties]

for i, row in grouped_cases.head(5).iterrows():
    text = row["segment_text"]

    parties = extract_parties_from_text(text)
    parties = [fix_party_entity(e) for e in parties]

    print(f"\nCase {i}")
    print(parties)

"""---
#  Part 5: Save Results & Export
---

##  Extract Results & Prepare Model B Input
"""

import re
import torch

# =========================
# CLEANING FUNCTIONS
# =========================
def clean_entity_text(text):
    text = text.replace("[UNK]", "")
    text = " ".join(text.split())
    return text.strip()

def remove_duplicate_entities(entities):
    seen = set()
    unique = []

    for e in entities:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            unique.append(e)

    return unique

def filter_entities(entities):
    clean = []

    for e in entities:
        txt = e["text"]

        if len(txt) < 4:
            continue
        if "..." in txt:
            continue
        if "النظام ونصها" in txt:
            continue
        if txt == "":
            continue

        clean.append(e)

    return clean

# =========================
# MODEL A ENTITY EXTRACTION
# =========================
def join_tokens(tokens):
    text = ""
    for tok in tokens:
        if tok.startswith("##"):
            text += tok[2:]
        else:
            if text:
                text += " "
            text += tok
    return text


def extract_entities_for_model_b(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entity_text = join_tokens(current_tokens)
                entities.append({
                    "text": clean_entity_text(entity_text),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entity_text = join_tokens(current_tokens)
                entities.append({
                    "text": clean_entity_text(entity_text),
                    "label": current_label
                })

            current_tokens = []
            current_label = None

    if current_tokens:
        entity_text = join_tokens(current_tokens)
        entities.append({
            "text": clean_entity_text(entity_text),
            "label": current_label
        })

    return entities


# =========================
# PARTY EXTRACTION (REGEX)
# =========================
def extract_parties_from_text(text):
    parties = []

    plaintiff_pattern = r"المدّ?عي\s*:\s*(.*?)(?=\s+المدّ?عى عليه\s*:|\n|$)"

    defendant_pattern = (
        r"المدّ?عى عليه\s*:\s*(.*?)"
        r"(?=\s+الحمدلله|\s+الحمد لله|\s+تتلخص|\s+وقائع|\s+الاسباب|\s+حكمت|\n|$)"
    )

    plaintiff = re.search(plaintiff_pattern, text)
    defendant = re.search(defendant_pattern, text)

    if plaintiff:
        parties.append({
            "text": clean_entity_text(plaintiff.group(1)),
            "label": "مدعي"
        })
    else:
        parties.append({
            "text": "[PLAINTIFF]",
            "label": "مدعي"
        })

    if defendant:
        parties.append({
            "text": clean_entity_text(defendant.group(1)),
            "label": "مدعى_عليه"
        })
    else:
        parties.append({
            "text": "[DEFENDANT]",
            "label": "مدعى_عليه"
        })

    return parties


def fix_party_entity(entity):
    text = entity["text"]
    label = entity["label"]

    if "..." in text or "(...)" in text:
        if label == "مدعي":
            text = "[PLAINTIFF]"
        elif label == "مدعى_عليه":
            text = "[DEFENDANT]"

    return {"text": text, "label": label}


# =========================
# FINAL PIPELINE FUNCTION
# =========================
def build_entities(text):

    # Model A
    entities = extract_entities_for_model_b(text)

    # Parties
    parties = extract_parties_from_text(text)
    parties = [fix_party_entity(e) for e in parties]

    # Merge
    entities.extend(parties)

    # Clean
    entities = [{**e, "text": clean_entity_text(e["text"])} for e in entities]
    entities = remove_duplicate_entities(entities)
    entities = filter_entities(entities)

    return entities

entities = build_entities(grouped_cases.iloc[0]["segment_text"])
print(entities)

for i, row in grouped_cases.head(5).iterrows():
    text = row["segment_text"]

    parties = extract_parties_from_text(text)
    parties = [fix_party_entity(e) for e in parties]

    print(f"\nCase {i}")
    print(parties)

"""# Build Model B Input with Cleaned and Enriched Entities"""

import pandas as pd

SEGMENTED_PATH = "/kaggle/input/datasets/ruofalshreef/segment/03_segmented (5).csv"

segmented_df = pd.read_csv(SEGMENTED_PATH)

print(segmented_df.shape)
segmented_df.head()

grouped_cases = (
    segmented_df.sort_values(["case_id", "segment_order"])
    .groupby("case_id")["segment_text"]
    .apply(lambda x: " ".join(x.astype(str)))
    .reset_index()
)

print("Number of cases:", len(grouped_cases))
grouped_cases.head()

model_b_data = []

for i, row in grouped_cases.iterrows():
    text = row["segment_text"]

    entities = build_entities(text)

    model_b_data.append({
        "case_id": row["case_id"],
        "case_text": text,
        "model_a_entities": entities
    })

    if i % 100 == 0:
        print(f"Processed {i}/{len(grouped_cases)}")

print("Done:", len(model_b_data))

import random

for i in random.sample(range(len(model_b_data)), 3):
    print(f"\n=== Case {i} ===")
    print("Text:", model_b_data[i]["case_text"][:200])
    print("Entities:", model_b_data[i]["model_a_entities"])

def filter_entities(entities):
    clean = []

    noise_phrases = [
        "النظام ونصها",
        "صحيفة الدعوى",
        "وباطلاع",
        "وبسؤاله",
        "وطالب",
        "رد",
        "السير في الدعوى",
        "مرفقاتها",
    ]

    for e in entities:
        txt = e["text"].strip()
        label = e["label"]

        if txt == "":
            continue

        if len(txt) < 4:
            continue

        if "[UNK]" in txt:
            continue

        if "..." in txt:
            continue

        if any(p in txt for p in noise_phrases):
            continue

        # لا نخلي كيان طويل جدًا لأنه غالبًا جملة كاملة مو entity
        if label in ["محكمة", "اسم_نظام", "مرجع_قانوني"] and len(txt.split()) > 8:
            continue

        clean.append({"text": txt, "label": label})

    return clean

model_b_data = []

for i, row in grouped_cases.iterrows():
    text = row["segment_text"]
    entities = build_entities(text)

    model_b_data.append({
        "case_id": row["case_id"],
        "case_text": text,
        "model_a_entities": entities
    })

    if i % 100 == 0:
        print(f"Processed {i}/{len(grouped_cases)}")

print("Done:", len(model_b_data))

import random

for i in random.sample(range(len(model_b_data)), 3):
    print(f"\n=== Case {i} ===")
    print("Text:", model_b_data[i]["case_text"][:200])
    print("Entities:")
    for e in model_b_data[i]["model_a_entities"]:
        print(" -", e)

def filter_entities(entities):
    clean = []

    noise_phrases = [
        "صحيفة الدعوى",
        "وباطلاع",
        "وبسؤاله",
        "السير في الدعوى",
        "جلسة",
        "حكمها",
        "مبنيا على",
        "على ما يلي",
        "وبناء على",
        "وبسؤال",
        "قررت",
    ]

    for e in entities:
        txt = e["text"].strip()
        label = e["label"]

        # ❌ حذف الفارغ والقصير
        if txt == "" or len(txt) < 4:
            continue

        # ❌ حذف نويز
        if "[UNK]" in txt or "..." in txt:
            continue

        if any(p in txt for p in noise_phrases):
            continue

        # ❌ لو طويل بزيادة (غالبًا جملة)
        if len(txt.split()) > 6:
            continue

        # ❌ تنظيف خاص للمحكمة
        if label == "محكمة" and "الدائرة" not in txt and "المحكمة" not in txt:
            continue

        clean.append({"text": txt, "label": label})

    return clean

model_b_data = []

for i, row in grouped_cases.iterrows():
    text = row["segment_text"]

    # 🔹 استخراج الكيانات (يشمل Model A + الأطراف + التنظيف)
    entities = build_entities(text)

    model_b_data.append({
        "case_id": row["case_id"],
        "case_text": text,
        "model_a_entities": entities
    })

    if i % 100 == 0:
        print(f"Processed {i}/{len(grouped_cases)}")

print("Done:", len(model_b_data))

import random

for i in random.sample(range(len(model_b_data)), 2):
    print(f"\n=== Case {i} ===")
    for e in model_b_data[i]["model_a_entities"]:
        print(e)

import json

print(json.dumps(model_b_data[0], ensure_ascii=False, indent=2))

print(json.dumps(model_b_data[4564], ensure_ascii=False, indent=2))

import random

for i in random.sample(range(len(model_b_data)), 3):
    print(f"\n=== Case {i} ===")
    print("Text snippet:", model_b_data[i]["case_text"][:200])
    print("Entities:")
    for e in model_b_data[i]["model_a_entities"]:
        print(" -", e)

import re
import torch

# =========================
# Date Validation
# =========================
def is_valid_date_entity(txt):
    txt = txt.strip()

    if not ("ه" in txt or "م" in txt):
        return False

    nums = re.findall(r"\d+", txt)

    if len(nums) < 3:
        return False

    year = int(nums[-1])

    if "ه" in txt and not (1300 <= year <= 1500):
        return False

    if "م" in txt and not (1900 <= year <= 2030):
        return False

    return True


# =========================
# Cleaning
# =========================
def clean_entity_text(text):
    text = str(text)
    text = text.replace("[UNK]", "")
    text = " ".join(text.split())
    return text.strip()


def remove_duplicate_entities(entities):
    seen = set()
    unique = []

    for e in entities:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            unique.append(e)

    return unique


def normalize_legal_label(label):
    """
    نحول مرجع_قانوني إلى رقم_مادة
    لأن Model B يحتاج رقم المادة بشكل واضح.
    """
    if label == "مرجع_قانوني":
        return "رقم_مادة"
    return label


def filter_entities(entities):
    clean = []

    noise_phrases = [
        "النظام ونصها",
        "صحيفة الدعوى",
        "وباطلاع",
        "وبسؤاله",
        "السير في الدعوى",
        "جلسة",
        "حكمها",
        "مبنيا على",
        "على ما يلي",
        "وبناء على",
        "وبسؤال",
        "قررت",
        "بنظر",
        "وطالب",
        "رد",
        "مرفقاتها",
    ]

    for e in entities:
        txt = clean_entity_text(e["text"])
        label = normalize_legal_label(e["label"])

        if txt == "" or len(txt) < 4:
            continue

        if "[UNK]" in txt or "..." in txt:
            continue

        if any(p in txt for p in noise_phrases):
            continue

        # لا نحذف النص الطويل إذا كان اسم نظام أو رقم مادة
        if label not in ["اسم_نظام", "رقم_مادة"] and len(txt.split()) > 8:
            continue

        # فلترة التواريخ الغلط أو الناقصة
        if label == "تاريخ" and not is_valid_date_entity(txt):
            continue

        clean.append({"text": txt, "label": label})

    return clean


# =========================
# Token Join
# =========================
def join_tokens(tokens):
    text = ""

    for tok in tokens:
        if tok.startswith("##"):
            text += tok[2:]
        else:
            if text:
                text += " "
            text += tok

    return text


# =========================
# Model A Entity Extraction
# =========================
label_list = [
    "O",
    "B-اسم_نظام",
    "B-تاريخ",
    "B-رقم_قضية",
    "B-مبلغ_مالي",
    "B-محكمة",
    "B-مرجع_قانوني",
    "I-اسم_نظام",
    "I-تاريخ",
    "I-رقم_قضية",
    "I-مبلغ_مالي",
    "I-محكمة",
    "I-مرجع_قانوني"
]


def extract_entities_for_model_b(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entities.append({
                    "text": clean_entity_text(join_tokens(current_tokens)),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entities.append({
                    "text": clean_entity_text(join_tokens(current_tokens)),
                    "label": current_label
                })

            current_tokens = []
            current_label = None

    if current_tokens:
        entities.append({
            "text": clean_entity_text(join_tokens(current_tokens)),
            "label": current_label
        })

    return entities


# =========================
# Rule-based Legal Reference Extraction
# احتياط مهم لرقم المادة واسم النظام
# =========================
def extract_legal_refs_rule_based(text):
    refs = []

    patterns = [
        r"المادة\s+(?:رقم\s*)?([0-9٠-٩]+)",
        r"المادة\s+([الأولىالثانيةالثالثةالرابعةالخامسةالسادسةالسابعةالثامنةالتاسعةالعاشرة]+)",
        r"الفقرة\s+(?:رقم\s*)?([0-9٠-٩]+)\s+من\s+المادة\s+(?:رقم\s*)?([0-9٠-٩]+)",
    ]

    for pattern in patterns:
        for match in re.finditer(pattern, text):
            refs.append({
                "text": clean_entity_text(match.group(0)),
                "label": "رقم_مادة"
            })

    return refs


def extract_law_names_rule_based(text):
    laws = []

    pattern = r"(نظام\s+[^\n،.؛:]{3,60}|اللائحة\s+[^\n،.؛:]{3,60})"

    stop_words = [
        "وبناء",
        "وحيث",
        "فإن",
        "وقد",
        "لما",
        "ثم",
        "عليه",
        "الدائرة",
        "المحكمة",
    ]

    for match in re.finditer(pattern, text):
        law_name = clean_entity_text(match.group(0))

        for stop in stop_words:
            if stop in law_name:
                law_name = law_name.split(stop)[0].strip()

        if len(law_name.split()) >= 2:
            laws.append({
                "text": law_name,
                "label": "اسم_نظام"
            })

    return laws


# =========================
# Party Extraction
# =========================
def extract_parties_from_text(text):
    parties = []

    plaintiff_pattern = r"المدّ?عي\s*:\s*(.*?)(?=\s+المدّ?عى عليه\s*:|\n|$)"

    defendant_pattern = (
        r"المدّ?عى عليه\s*:\s*(.*?)"
        r"(?=\s+الحمدلله|\s+الحمد لله|\s+تتلخص|\s+تتحصل|\s+وقائع|\s+الاسباب|\s+الأسباب|\s+حكمت|\n|$)"
    )

    plaintiff = re.search(plaintiff_pattern, text)
    defendant = re.search(defendant_pattern, text)

    if plaintiff:
        parties.append({
            "text": clean_entity_text(plaintiff.group(1)),
            "label": "مدعي"
        })
    else:
        parties.append({
            "text": "[PLAINTIFF]",
            "label": "مدعي"
        })

    if defendant:
        parties.append({
            "text": clean_entity_text(defendant.group(1)),
            "label": "مدعى_عليه"
        })
    else:
        parties.append({
            "text": "[DEFENDANT]",
            "label": "مدعى_عليه"
        })

    return parties


def fix_party_entity(entity):
    text = entity["text"]
    label = entity["label"]

    if "..." in text or "(...)" in text or "....." in text:
        if label == "مدعي":
            text = "[PLAINTIFF]"
        elif label == "مدعى_عليه":
            text = "[DEFENDANT]"

    return {"text": text, "label": label}


# =========================
# Final Build Function
# =========================
def build_entities(text):
    entities = []

    # 1) Model A extraction
    entities.extend(extract_entities_for_model_b(text))

    # 2) Rule-based backup for رقم المادة
    entities.extend(extract_legal_refs_rule_based(text))

    # 3) Rule-based backup for اسم النظام
    entities.extend(extract_law_names_rule_based(text))

    # 4) Parties extraction
    parties = extract_parties_from_text(text)
    parties = [fix_party_entity(e) for e in parties]
    entities.extend(parties)

    # 5) Final cleaning
    entities = [
        {
            "text": clean_entity_text(e["text"]),
            "label": normalize_legal_label(e["label"])
        }
        for e in entities
    ]

    entities = remove_duplicate_entities(entities)
    entities = filter_entities(entities)

    return entities

def filter_entities(entities):
    clean = []

    noise_phrases = [
        "النظام ونصها", "صحيفة الدعوى", "وباطلاع", "وبسؤاله",
        "السير في الدعوى", "جلسة", "حكمها", "مبنيا على",
        "على ما يلي", "وبناء على", "وبسؤال", "قررت",
        "بنظر", "وطالب", "رد", "مرفقاتها",
        "كما نصت", "وطلب", "إلزام", "المدعي", "المدعى",
        "وبناء"
    ]

    bad_endings = ["وبناء", "كما نصت", "من", "و"]

    for e in entities:
        txt = clean_entity_text(e["text"])
        label = normalize_legal_label(e["label"])

        if txt == "" or len(txt) < 4:
            continue

        if "[UNK]" in txt or "..." in txt:
            continue

        if any(p in txt for p in noise_phrases):
            continue

        if any(txt.endswith(end) for end in bad_endings):
            continue

        if label == "تاريخ" and not is_valid_date_entity(txt):
            continue

        if label == "رقم_مادة":
            if not re.search(r"المادة\s+(?:رقم\s*)?[0-9٠-٩]+", txt):
                continue

        if label == "اسم_نظام":
            if not (txt.startswith("نظام") or txt.startswith("اللائحة")):
                continue

        if label not in ["اسم_نظام", "رقم_مادة"] and len(txt.split()) > 8:
            continue

        clean.append({"text": txt, "label": label})

    return clean

def extract_courts_rule_based(text):
    courts = []

    pattern = r"(المحكمة\s+[^\n،.؛:]{3,40})"

    stop_words = ["وبناء", "وحيث", "فإن", "وقد", "لدى"]

    for match in re.finditer(pattern, text):
        court = clean_entity_text(match.group(0))

        for stop in stop_words:
            if stop in court:
                court = court.split(stop)[0].strip()

        if len(court.split()) >= 2:
            courts.append({
                "text": court,
                "label": "محكمة"
            })

    return courts



# =========================
# Test Model A Entities
# =========================

test_text = """
الحمد لله والصلاة والسلام على رسول الله أما بعد:
لدى المحكمة التجارية وبناء على القضية رقم 4470913933 لعام 1444ه
المدعي: شركة الشبكة الأساسية للتجارة والمقاولات
المدعى عليه: عمر ابراهيم عمر الرشود

وحيث نصت المادة رقم 76 من نظام المحاكم التجارية،
كما نصت المادة 24 من نظام الإثبات،
وطلب المدعي إلزام المدعى عليه بدفع مبلغ 50000 ريال بتاريخ 10/11/1436ه.
"""

entities = build_entities(test_text)

for e in entities:
    print(e)

import re
import torch

# =========================
# Date Validation
# =========================
def is_valid_date_entity(txt):
    txt = txt.strip()

    if not ("ه" in txt or "م" in txt):
        return False

    nums = re.findall(r"\d+", txt)

    if len(nums) < 3:
        return False

    year = int(nums[-1])

    if "ه" in txt and not (1300 <= year <= 1500):
        return False

    if "م" in txt and not (1900 <= year <= 2030):
        return False

    return True


# =========================
# Cleaning
# =========================
def clean_entity_text(text):
    text = str(text)
    text = text.replace("[UNK]", "")
    text = " ".join(text.split())
    return text.strip()


def normalize_legal_label(label):
    if label == "مرجع_قانوني":
        return "رقم_مادة"
    return label


def remove_duplicate_entities(entities):
    seen = set()
    unique = []

    for e in entities:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            unique.append(e)

    return unique


def filter_entities(entities):
    clean = []

    noise_phrases = [
        "النظام ونصها", "صحيفة الدعوى", "وباطلاع", "وبسؤاله",
        "السير في الدعوى", "جلسة", "حكمها", "مبنيا على",
        "على ما يلي", "وبناء على", "وبسؤال", "قررت",
        "بنظر", "وطالب", "رد", "مرفقاتها",
        "كما نصت", "وطلب", "إلزام", "المدعي", "المدعى",
        "وبناء"
    ]

    bad_endings = ["وبناء", "كما نصت", "من", "و"]

    for e in entities:
        txt = clean_entity_text(e["text"])
        label = normalize_legal_label(e["label"])

        if txt == "" or len(txt) < 4:
            continue

        if "[UNK]" in txt or "..." in txt:
            continue

        if any(p in txt for p in noise_phrases):
            continue

        if any(txt.endswith(end) for end in bad_endings):
            continue

        if label == "تاريخ" and not is_valid_date_entity(txt):
            continue

        if label == "رقم_مادة":
            if not re.search(r"المادة\s+(?:رقم\s*)?[0-9٠-٩]+", txt):
                continue

        if label == "اسم_نظام":
            if not (txt.startswith("نظام") or txt.startswith("اللائحة")):
                continue

        if label == "محكمة":
            if not txt.startswith("المحكمة"):
                continue

        if label not in ["اسم_نظام", "رقم_مادة", "محكمة"] and len(txt.split()) > 8:
            continue

        clean.append({"text": txt, "label": label})

    return clean


# =========================
# Token Join
# =========================
def join_tokens(tokens):
    text = ""

    for tok in tokens:
        if tok.startswith("##"):
            text += tok[2:]
        else:
            if text:
                text += " "
            text += tok

    return text


# =========================
# Model A Entity Extraction
# =========================
label_list = [
    "O",
    "B-اسم_نظام",
    "B-تاريخ",
    "B-رقم_قضية",
    "B-مبلغ_مالي",
    "B-محكمة",
    "B-مرجع_قانوني",
    "I-اسم_نظام",
    "I-تاريخ",
    "I-رقم_قضية",
    "I-مبلغ_مالي",
    "I-محكمة",
    "I-مرجع_قانوني"
]


def extract_entities_for_model_b(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entities.append({
                    "text": clean_entity_text(join_tokens(current_tokens)),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entities.append({
                    "text": clean_entity_text(join_tokens(current_tokens)),
                    "label": current_label
                })

            current_tokens = []
            current_label = None

    if current_tokens:
        entities.append({
            "text": clean_entity_text(join_tokens(current_tokens)),
            "label": current_label
        })

    return entities


# =========================
# Rule-based Legal Reference Extraction
# =========================
def extract_legal_refs_rule_based(text):
    refs = []

    patterns = [
        r"المادة\s+(?:رقم\s*)?[0-9٠-٩]+",
        r"الفقرة\s+(?:رقم\s*)?[0-9٠-٩]+\s+من\s+المادة\s+(?:رقم\s*)?[0-9٠-٩]+",
    ]

    for pattern in patterns:
        for match in re.finditer(pattern, text):
            refs.append({
                "text": clean_entity_text(match.group(0)),
                "label": "رقم_مادة"
            })

    return refs


def extract_law_names_rule_based(text):
    laws = []

    pattern = r"(نظام\s+[^\n،.؛:]{3,60}|اللائحة\s+[^\n،.؛:]{3,60})"

    stop_words = [
        "وبناء", "وحيث", "فإن", "وقد", "لما",
        "ثم", "عليه", "الدائرة", "المحكمة",
        "كما نصت", "وطلب", "إلزام", "المدعي", "المدعى"
    ]

    for match in re.finditer(pattern, text):
        law_name = clean_entity_text(match.group(0))

        for stop in stop_words:
            if stop in law_name:
                law_name = law_name.split(stop)[0].strip()

        if len(law_name.split()) >= 2:
            laws.append({
                "text": law_name,
                "label": "اسم_نظام"
            })

    return laws


# =========================
# Rule-based Court Extraction
# =========================
def extract_courts_rule_based(text):
    courts = []

    pattern = r"(المحكمة\s+[^\n،.؛:]{3,40})"

    stop_words = [
        "وبناء", "وحيث", "فإن", "وقد", "لدى",
        "كما", "وطلب", "إلزام", "المدعي", "المدعى"
    ]

    for match in re.finditer(pattern, text):
        court = clean_entity_text(match.group(0))

        for stop in stop_words:
            if stop in court:
                court = court.split(stop)[0].strip()

        if len(court.split()) >= 2:
            courts.append({
                "text": court,
                "label": "محكمة"
            })

    return courts


# =========================
# Party Extraction
# =========================
def extract_parties_from_text(text):
    parties = []

    plaintiff_pattern = r"المدّ?عي\s*:\s*(.*?)(?=\s+المدّ?عى عليه\s*:|\n|$)"

    defendant_pattern = (
        r"المدّ?عى عليه\s*:\s*(.*?)"
        r"(?=\s+الحمدلله|\s+الحمد لله|\s+تتلخص|\s+تتحصل|\s+وقائع|\s+الاسباب|\s+الأسباب|\s+حكمت|\n|$)"
    )

    plaintiff = re.search(plaintiff_pattern, text)
    defendant = re.search(defendant_pattern, text)

    if plaintiff:
        parties.append({
            "text": clean_entity_text(plaintiff.group(1)),
            "label": "مدعي"
        })
    else:
        parties.append({
            "text": "[PLAINTIFF]",
            "label": "مدعي"
        })

    if defendant:
        parties.append({
            "text": clean_entity_text(defendant.group(1)),
            "label": "مدعى_عليه"
        })
    else:
        parties.append({
            "text": "[DEFENDANT]",
            "label": "مدعى_عليه"
        })

    return parties


def fix_party_entity(entity):
    text = entity["text"]
    label = entity["label"]

    if "..." in text or "(...)" in text or "....." in text:
        if label == "مدعي":
            text = "[PLAINTIFF]"
        elif label == "مدعى_عليه":
            text = "[DEFENDANT]"

    return {"text": text, "label": label}


# =========================
# Final Build Function
# =========================
def build_entities(text):
    entities = []

    # 1) Model A extraction
    entities.extend(extract_entities_for_model_b(text))

    # 2) Rule-based backup for رقم المادة
    entities.extend(extract_legal_refs_rule_based(text))

    # 3) Rule-based backup for اسم النظام
    entities.extend(extract_law_names_rule_based(text))

    # 4) Rule-based backup for المحكمة
    entities.extend(extract_courts_rule_based(text))

    # 5) Parties extraction
    parties = extract_parties_from_text(text)
    parties = [fix_party_entity(e) for e in parties]
    entities.extend(parties)

    # 6) Final cleaning
    entities = [
        {
            "text": clean_entity_text(e["text"]),
            "label": normalize_legal_label(e["label"])
        }
        for e in entities
    ]

    entities = remove_duplicate_entities(entities)
    entities = filter_entities(entities)

    return entities

# =========================
# Final Test
# =========================

test_text = """
الحمد لله والصلاة والسلام على رسول الله أما بعد:
لدى المحكمة التجارية وبناء على القضية رقم 4470913933 لعام 1444ه
المدعي: شركة الشبكة الأساسية للتجارة والمقاولات
المدعى عليه: عمر ابراهيم عمر الرشود

وحيث نصت المادة رقم 76 من نظام المحاكم التجارية،
كما نصت المادة 24 من نظام الإثبات،
وطلب المدعي إلزام المدعى عليه بدفع مبلغ 50000 ريال بتاريخ 10/11/1436ه.
"""

entities = build_entities(test_text)

for e in entities:
    print(e)

model_b_data = []

for idx, (_, row) in enumerate(grouped_cases.iterrows()):
    text = str(row["segment_text"])

    # لو النص طويل جدًا نقصّه بشكل ذكي (اختياري)
    if len(text) > 2000:
        text = text[:2000]

    entities = build_entities(text)

    model_b_data.append({
        "case_id": row["case_id"],
        "case_text": text,
        "model_a_entities": entities
    })

    # Progress
    if idx % 100 == 0:
        print(f"Processed {idx}/{len(grouped_cases)}")

print("Done:", len(model_b_data))

import random

for i in random.sample(range(len(model_b_data)), 2):
    print("\n=== Case ===")
    print("Text:", model_b_data[i]["case_text"][:200])
    print("Entities:", model_b_data[i]["model_a_entities"])

import re
import torch

# =========================
# Date Validation
# =========================
def is_valid_date_entity(txt):
    txt = txt.strip()

    if not ("ه" in txt or "م" in txt):
        return False

    nums = re.findall(r"\d+", txt)

    if len(nums) < 3:
        return False

    year = int(nums[-1])

    if "ه" in txt and not (1300 <= year <= 1500):
        return False

    if "م" in txt and not (1900 <= year <= 2030):
        return False

    return True


# =========================
# Cleaning
# =========================
def clean_entity_text(text):
    text = str(text)
    text = text.replace("[UNK]", "")
    text = text.replace("ـ", "")
    text = " ".join(text.split())
    return text.strip()


def normalize_legal_label(label):
    if label == "مرجع_قانوني":
        return "رقم_مادة"
    return label


def remove_duplicate_entities(entities):
    seen = set()
    unique = []

    for e in entities:
        txt = clean_entity_text(e["text"])
        label = normalize_legal_label(e["label"])

        key = (txt, label)

        if key not in seen:
            seen.add(key)
            unique.append({"text": txt, "label": label})

    return unique


def keep_longest_entities(entities):
    final = []

    for e in entities:
        txt = e["text"]
        label = e["label"]

        shorter_duplicate = False

        for other in entities:
            if e == other:
                continue

            if label == other["label"]:
                if txt in other["text"] and len(other["text"]) > len(txt):
                    shorter_duplicate = True
                    break

        if not shorter_duplicate:
            final.append(e)

    return final


def filter_entities(entities):
    clean = []

    noise_phrases = [
        "النظام ونصها", "صحيفة الدعوى", "وباطلاع", "وبسؤاله",
        "السير في الدعوى", "جلسة", "حكمها", "مبنيا على",
        "على ما يلي", "وبناء على", "وبسؤال", "قررت",
        "بنظر", "وطالب", "رد", "مرفقاتها",
        "كما نصت", "وطلب", "إلزام", "المدعي", "المدعى",
        "وبناء", "ففهم"
    ]

    bad_endings = ["وبناء", "كما نصت", "من", "و", "بمدينة"]

    bad_law_words = [
        "ففهم", "فهم", "ونصها", "عليه", "بناء",
        "المدعي", "المدعى", "وطلب", "إلزام"
    ]

    for e in entities:
        txt = clean_entity_text(e["text"])
        label = normalize_legal_label(e["label"])

        if txt == "" or len(txt) < 4:
            continue

        if "[UNK]" in txt or "..." in txt:
            continue

        if any(p in txt for p in noise_phrases):
            continue

        if any(txt.endswith(end) for end in bad_endings):
            continue

        if label == "تاريخ" and not is_valid_date_entity(txt):
            continue

        if label == "رقم_مادة":
            if not re.search(r"المادة\s+(?:رقم\s*)?[0-9٠-٩]+", txt):
                continue

        if label == "اسم_نظام":
            if not (txt.startswith("نظام") or txt.startswith("اللائحة")):
                continue

            if len(txt.split()) < 3:
                continue

            if any(w in txt for w in bad_law_words):
                continue

        if label == "محكمة":
            if not txt.startswith("المحكمة"):
                continue

            if len(txt.split()) < 2:
                continue

        if label not in ["اسم_نظام", "رقم_مادة", "محكمة"] and len(txt.split()) > 8:
            continue

        clean.append({"text": txt, "label": label})

    return clean


# =========================
# Token Join
# =========================
def join_tokens(tokens):
    text = ""

    for tok in tokens:
        if tok.startswith("##"):
            text += tok[2:]
        else:
            if text:
                text += " "
            text += tok

    return text


# =========================
# Model A Entity Extraction
# =========================
label_list = [
    "O",
    "B-اسم_نظام",
    "B-تاريخ",
    "B-رقم_قضية",
    "B-مبلغ_مالي",
    "B-محكمة",
    "B-مرجع_قانوني",
    "I-اسم_نظام",
    "I-تاريخ",
    "I-رقم_قضية",
    "I-مبلغ_مالي",
    "I-محكمة",
    "I-مرجع_قانوني"
]


def extract_entities_for_model_b(text):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    with torch.no_grad():
        outputs = model(**inputs)

    preds = torch.argmax(outputs.logits, dim=2)[0]
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    labels = [label_list[p.item()] for p in preds]

    entities = []
    current_tokens = []
    current_label = None

    for token, label in zip(tokens, labels):
        if token in ["[CLS]", "[SEP]", "[PAD]"]:
            continue

        if label.startswith("B-"):
            if current_tokens:
                entities.append({
                    "text": clean_entity_text(join_tokens(current_tokens)),
                    "label": current_label
                })

            current_tokens = [token]
            current_label = label[2:]

        elif label.startswith("I-") and current_label == label[2:]:
            current_tokens.append(token)

        else:
            if current_tokens:
                entities.append({
                    "text": clean_entity_text(join_tokens(current_tokens)),
                    "label": current_label
                })

            current_tokens = []
            current_label = None

    if current_tokens:
        entities.append({
            "text": clean_entity_text(join_tokens(current_tokens)),
            "label": current_label
        })

    return entities


# =========================
# Rule-based Legal Reference Extraction
# =========================
def extract_legal_refs_rule_based(text):
    refs = []

    patterns = [
        r"المادة\s+(?:رقم\s*)?[0-9٠-٩]+",
        r"الفقرة\s+(?:رقم\s*)?[0-9٠-٩]+\s+من\s+المادة\s+(?:رقم\s*)?[0-9٠-٩]+",
    ]

    for pattern in patterns:
        for match in re.finditer(pattern, text):
            refs.append({
                "text": clean_entity_text(match.group(0)),
                "label": "رقم_مادة"
            })

    return refs


def extract_law_names_rule_based(text):
    laws = []

    pattern = r"(نظام\s+[^\n،.؛:]{3,70}|اللائحة\s+[^\n،.؛:]{3,70})"

    stop_words = [
        "وبناء", "وحيث", "فإن", "وقد", "لما", "ثم",
        "عليه", "الدائرة", "المحكمة", "كما نصت",
        "وطلب", "إلزام", "المدعي", "المدعى", "ففهم"
    ]

    for match in re.finditer(pattern, text):
        law_name = clean_entity_text(match.group(0))

        for stop in stop_words:
            if stop in law_name:
                law_name = law_name.split(stop)[0].strip()

        if len(law_name.split()) >= 3:
            laws.append({
                "text": law_name,
                "label": "اسم_نظام"
            })

    return laws


# =========================
# Rule-based Court Extraction
# =========================
def extract_courts_rule_based(text):
    courts = []

    pattern = r"(المحكمة\s+[^\n،.؛:]{3,60})"

    stop_words = [
        "وبناء", "وحيث", "فإن", "وقد", "لدى",
        "كما", "وطلب", "إلزام", "المدعي", "المدعى"
    ]

    for match in re.finditer(pattern, text):
        court = clean_entity_text(match.group(0))

        for stop in stop_words:
            if stop in court:
                court = court.split(stop)[0].strip()

        if len(court.split()) >= 2:
            courts.append({
                "text": court,
                "label": "محكمة"
            })

    return courts


# =========================
# Party Extraction
# =========================
def extract_parties_from_text(text):
    parties = []

    plaintiff_pattern = r"المدّ?عي\s*:\s*(.*?)(?=\s+المدّ?عى عليه\s*:|\s+المدّ?عي عليه\s*:|\n|$)"

    defendant_pattern = (
        r"(?:المدّ?عى عليه|المدّ?عي عليه)\s*:\s*(.*?)"
        r"(?=\s+الحمدلله|\s+الحمد لله|\s+تتلخص|\s+تتحصل|\s+وقائع|\s+الاسباب|\s+الأسباب|\s+حكمت|\n|$)"
    )

    plaintiff = re.search(plaintiff_pattern, text)
    defendant = re.search(defendant_pattern, text)

    if plaintiff:
        p_text = clean_entity_text(plaintiff.group(1))
        if "..." in p_text or "(...)" in p_text or len(p_text) < 3:
            p_text = "[PLAINTIFF]"
        parties.append({"text": p_text, "label": "مدعي"})
    else:
        parties.append({"text": "[PLAINTIFF]", "label": "مدعي"})

    if defendant:
        d_text = clean_entity_text(defendant.group(1))
        if "..." in d_text or "(...)" in d_text or len(d_text) < 3:
            d_text = "[DEFENDANT]"
        parties.append({"text": d_text, "label": "مدعى_عليه"})
    else:
        parties.append({"text": "[DEFENDANT]", "label": "مدعى_عليه"})

    return parties


# =========================
# Final Build Function
# =========================
def build_entities(text):
    entities = []

    text = str(text)

    # 1) Model A extraction
    entities.extend(extract_entities_for_model_b(text))

    # 2) Rule-based backup for رقم المادة
    entities.extend(extract_legal_refs_rule_based(text))

    # 3) Rule-based backup for اسم النظام
    entities.extend(extract_law_names_rule_based(text))

    # 4) Rule-based backup for المحكمة
    entities.extend(extract_courts_rule_based(text))

    # 5) Parties extraction
    entities.extend(extract_parties_from_text(text))

    # 6) Final cleaning
    entities = [
        {
            "text": clean_entity_text(e["text"]),
            "label": normalize_legal_label(e["label"])
        }
        for e in entities
    ]

    entities = remove_duplicate_entities(entities)
    entities = filter_entities(entities)
    entities = keep_longest_entities(entities)

    return entities

# =========================
# Run Model A on All Grouped Cases
# =========================

model_b_data = []

for idx, (_, row) in enumerate(grouped_cases.iterrows()):
    text = str(row["segment_text"])

    entities = build_entities(text)

    model_b_data.append({
        "case_id": row["case_id"],
        "case_text": text,
        "model_a_entities": entities
    })

    if idx % 100 == 0:
        print(f"Processed {idx}/{len(grouped_cases)}")

print("Done:", len(model_b_data))

import random

for i in random.sample(range(len(model_b_data)), 3):
    print(f"\n=== Case {i} ===")
    print("Case ID:", model_b_data[i]["case_id"])
    print("Text:", model_b_data[i]["case_text"][:300])
    print("Entities:")
    for e in model_b_data[i]["model_a_entities"]:
        print(e)

"""#  Save Model B Input Data"""

# =========================
# Save Model B Input Data
# =========================

import json

output_path = "/content/model_b_input_data.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for item in model_b_data:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("Saved to:", output_path)
print("Total cases:", len(model_b_data))

# =========================
# Quick Check Saved File
# =========================

with open("/content/model_b_input_data.jsonl", "r", encoding="utf-8") as f:
    for i in range(3):
        line = json.loads(f.readline())
        print("\n=== Case ===")
        print("Case ID:", line["case_id"])
        print("Text:", line["case_text"][:300])
        print("Entities:", line["model_a_entities"][:10])



import json

baseline_path = "/kaggle/input/datasets/ruofalshreef/lawbase/01_baseline_laws copy.jsonl"

KNOWN_LAWS = set()

with open(baseline_path, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        # حسب ملفك (جربي الاثنين)
        law_name = item.get("law_name") or item.get("system_name")

        if law_name:
            KNOWN_LAWS.add(law_name.strip())

print("Loaded laws:", len(KNOWN_LAWS))

def format_entities_for_prompt(entities):
    formatted = []

    for e in entities:
        formatted.append(f"{e['label']}: {e['text']}")

    return "\n".join(formatted)

def build_model_b_prompt(case):
    text = case["case_text"]
    entities = case["model_a_entities"]

    entities_text = format_entities_for_prompt(entities)

    prompt = f"""
You are a legal AI assistant specialized in Saudi commercial law.

Given the following case and extracted entities, perform the task carefully:

Case Text:
{text[:1500]}

Extracted Entities:
{entities_text}

Instructions:
- Ignore noisy or incomplete entities.
- Focus on valid law names and article numbers.
- Identify the legal issue.
- Explain the legal reasoning.
- Generate a structured legal scenario.

Output:
"""

    return prompt

import random

for i in random.sample(range(len(model_b_data)), 2):
    case = model_b_data[i]

    prompt = build_model_b_prompt(case)

    print("\n" + "="*80)
    print(prompt[:1000])

import re

def normalize_model_b_entities(entities):
    cleaned = []

    for e in entities:
        txt = str(e["text"]).strip()
        label = e["label"]

        # =========================
        # اسم النظام باستخدام baseline
        # =========================
        if label == "اسم_نظام":
            matched = None

            for law in KNOWN_LAWS:
                if law in txt:
                    matched = law
                    break

            if matched:
                cleaned.append({
                    "text": matched,
                    "label": "اسم_نظام"
                })

        # =========================
        # المحكمة
        # =========================
        elif label == "محكمة":
            match = re.search(r"(المحكمة\s+[^\n،.]{3,40})", txt)
            if match:
                court = match.group(1).strip()

                for stop in ["ذكر", "جاء", "الصادر", "بدعوى", "رقم"]:
                    if stop in court:
                        court = court.split(stop)[0].strip()

                cleaned.append({
                    "text": court,
                    "label": "محكمة"
                })

        # =========================
        # باقي الكيانات
        # =========================
        else:
            cleaned.append({
                "text": txt,
                "label": label
            })

    # إزالة التكرار
    seen = set()
    final = []

    for e in cleaned:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            final.append(e)

    return final

for item in model_b_data:
    item["model_a_entities"] = normalize_model_b_entities(
        item["model_a_entities"]
    )

print("Cleaned:", len(model_b_data))

import json

output_path = "/kaggle/working/model_b_input_data_clean.jsonl"

with open(output_path, "w", encoding="utf-8") as f:
    for item in model_b_data:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("Saved:", output_path)
print("Total cases:", len(model_b_data))

import random

for i in random.sample(range(len(model_b_data)), 2):
    print("\n=== Case ===")
    print("Case ID:", model_b_data[i]["case_id"])
    print("Entities:", model_b_data[i]["model_a_entities"][:15])

import re

def normalize_model_b_entities(entities):
    cleaned = []

    for e in entities:
        txt = str(e["text"]).strip()
        label = e["label"]

        # =========================
        # اسم النظام (baseline)
        # =========================
        if label == "اسم_نظام":
            for law in KNOWN_LAWS:
                if law in txt:
                    cleaned.append({
                        "text": law,
                        "label": "اسم_نظام"
                    })
                    break

        # =========================
        # المحكمة (تنظيف قوي)
        # =========================
        elif label == "محكمة":
            match = re.search(r"(المحكمة\s+[^\n،.]{3,40})", txt)

            if match:
                court = match.group(1).strip()

                # قص الزوائد
                for stop in ["بصحيفة", "وهي", "في", "ذلك", "تاريخ", "ذكر", "جاء"]:
                    if stop in court:
                        court = court.split(stop)[0].strip()

                cleaned.append({
                    "text": court,
                    "label": "محكمة"
                })

        # =========================
        # باقي الكيانات
        # =========================
        else:
            cleaned.append({
                "text": txt,
                "label": label
            })

    # =========================
    # إزالة التكرار + اختيار الأطول
    # =========================
    final = []

    for e in cleaned:
        txt = e["text"]
        label = e["label"]

        is_short = False

        for other in cleaned:
            if e == other:
                continue

            if label == other["label"]:
                if txt in other["text"] and len(other["text"]) > len(txt):
                    is_short = True
                    break

        if not is_short:
            final.append(e)

    return final

for item in model_b_data:
    item["model_a_entities"] = normalize_model_b_entities(
        item["model_a_entities"]
    )

print("Cleaned again ✅")

for item in model_b_data:
    item["model_a_entities"] = normalize_model_b_entities(
        item["model_a_entities"]
    )

print("Cleaned again ✅")

import random

for i in random.sample(range(len(model_b_data)), 2):
    print("\n=== Case ===")
    print("Case ID:", model_b_data[i]["case_id"])
    print("Entities:")

    for e in model_b_data[i]["model_a_entities"]:
        print(e)

import re

COURT_PATTERNS = [
    r"المحكمة التجارية بالرياض",
    r"المحكمة التجارية بجدة",
    r"المحكمة التجارية بالدمام",
    r"المحكمة العامة بالرياض",
    r"المحكمة العامة بجدة",
    r"المحكمة العامة بالدمام",
    r"المحكمة المختصة",
    r"المحكمة التجارية",
    r"المحكمة العامة",
]

def normalize_model_b_entities(entities):
    cleaned = []

    for e in entities:
        txt = str(e["text"]).strip()
        label = e["label"]

        if label == "اسم_نظام":
            for law in KNOWN_LAWS:
                if law in txt:
                    cleaned.append({"text": law, "label": "اسم_نظام"})
                    break

        elif label == "محكمة":
            matched_court = None

            for pattern in COURT_PATTERNS:
                if re.search(pattern, txt):
                    matched_court = pattern
                    break

            if matched_court:
                cleaned.append({"text": matched_court, "label": "محكمة"})

        else:
            cleaned.append({"text": txt, "label": label})

    # remove duplicates
    seen = set()
    final = []

    for e in cleaned:
        key = (e["text"], e["label"])
        if key not in seen:
            seen.add(key)
            final.append(e)

    return final

for item in model_b_data:
    item["model_a_entities"] = normalize_model_b_entities(
        item["model_a_entities"]
    )

print("Court cleaning done ✅")

import random

for i in random.sample(range(len(model_b_data)), 2):
    print("\n=== Case ===")
    print("Case ID:", model_b_data[i]["case_id"])
    for e in model_b_data[i]["model_a_entities"]:
        print(e)

import json

final_path = "/kaggle/working/model_b_input_clean_final.jsonl"

with open(final_path, "w", encoding="utf-8") as f:
    for item in model_b_data:
        f.write(json.dumps(item, ensure_ascii=False) + "\n")

print("Saved:", final_path)
print("Total:", len(model_b_data))

import os
print(os.listdir("/kaggle/working"))

def format_entities_for_prompt(entities):
    return "\n".join([f"- {e['label']}: {e['text']}" for e in entities])


def build_model_b_prompt(case):
    return f"""
You are Model B in the Tri-Model Smart Justice framework.

Task:
Generate a structured Saudi commercial legal scenario based on the case text and Model A extracted entities.

Case Text:
{case["case_text"][:1800]}

Model A Extracted Entities:
{format_entities_for_prompt(case["model_a_entities"])}

Instructions:
- Ignore noisy, duplicated, or incomplete entities.
- Use only valid legal systems and article numbers.
- Identify the legal dispute.
- Extract the parties' claims.
- Explain the legal reasoning briefly.
- Generate a structured scenario suitable for Model C prediction.

Output Format:
1. Case Summary:
2. Plaintiff Claim:
3. Defendant Response:
4. Legal Issue:
5. Relevant Laws/Articles:
6. Court Reasoning:
7. Expected Outcome:
"""

case = model_b_data[0]
prompt = build_model_b_prompt(case)

print(prompt[:2500])

import json

prompt_path = "/kaggle/working/model_b_prompts_final.jsonl"

with open(prompt_path, "w", encoding="utf-8") as f:
    for item in model_b_data:
        prompt_item = {
            "case_id": item["case_id"],
            "prompt": build_model_b_prompt(item)
        }
        f.write(json.dumps(prompt_item, ensure_ascii=False) + "\n")

print("Saved:", prompt_path)
print("Total prompts:", len(model_b_data))

with open(prompt_path, "r", encoding="utf-8") as f:
    first = json.loads(f.readline())

print(first["case_id"])
print(first["prompt"][:1500])

import zipfile
import os

zip_path = "/kaggle/working/model_b_files.zip"

with zipfile.ZipFile(zip_path, 'w') as z:
    for file in os.listdir("/kaggle/working"):
        if file.endswith(".jsonl"):
            z.write(f"/kaggle/working/{file}", file)

print("ZIP created:", zip_path)

from IPython.display import FileLink
FileLink("/kaggle/working/model_b_files.zip")